version: "3.8"
services:
  catalog-service:
    depends_on:
      config-service:
        condition: service_healthy
      polar-postgres:
        condition: service_started
    image: "catalog-service"
    build: .
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb-catalog
      - SPRING_PROFILES_ACTIVE=testData
  polar-postgres:
    image: "postgres:latest"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=serdar
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=polardb-catalog
  config-service:
    image: "ghcr.io/serdarahmanov/config-service:latest"
    container_name: "config-service"
    ports:
      - 8888:8888
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
