spring:
  application:
    name: catalog-service

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://config-service:8888
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        max-interval: 10000
        multiplier: 1.5

  #it is for resource binding
  datasource:
    #  docker run --name polar-postgres -e POSTGRES_USER=serdar -e POSTGRES_PASSWORD=1234 -e POSTGRES_DB=polardb-catalog -p 5432:5432 -d postgres:latest
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    username: serdar
    password: 1234
    hikari:
      #      maximum time to spend waiting to get a connection from the pool
      connection-timeout: 2000
      maximum-pool-size: 5

  #  By default, Spring loads sql files  when using in-memory dbs. To make it load automatically
#  but now , we will use Flyway to load sql files so we do not need automatic loading.
#  sql:
#    init:
#          mode: always




# By default, the actuator does not expose the endpoint to refresh the app.
# So we are configuring it manually.
management:
  endpoints:
    web:
      exposure:
        include: refresh



server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

#      Custom property defining.
polar:
  greeting: Welcome to Polar Book Shop from application.yml property file :)



